### ISSUE TITLE
S3 Bucket size

### ISSUE THREAD

**Issue by mahmoudhakam** [EMCECS/ecs-object-client-java#102]
The sdk did not offer a method to get information about bucket size or actual usage of the bucket

**Comment by dunedodo** [comment]
> The sdk did not offer a method to get information about bucket size or actual usage of the bucket

Hi @mahmoudhakam , could you help clarify "actual usage" here? are you talking about number of objects and size?

**Comment by dunedodo** [comment]
Hi @mahmoudhakam As it has been months from your last updates, we are going to close the issue in weeks. Please do not hesitate to contact us if you have any detailed requirements.

**Comment by dunedodo** [comment]
1.
