### ISSUE TITLE
CreateBucketRequest missing setServerSideEncryptionEnabled()

### ISSUE THREAD

**Issue by jasoncwik** [EMCECS/ecs-object-client-java#12]
CreateBucketRequest is missing D@RE bucket creation:

http://emcecs.github.io/ecs-object-client-java/latest/javadoc/com/emc/object/s3/request/CreateBucketRequest.html

Need to add support for `x-emc-server-side-encryption-enabled`

http://doc.isilon.com/ECS/3.0/API/S3BucketOperations_createBucket_3e75383a5992a6d15fb81e872e46e256_ba672412ac371bb6cf4e69291344510e_detail.html

**Comment by jasoncwik** [comment]
Also missing `x-emc-compliance-enabled`

**Comment by twincitiesguy** [comment]
Fixed in v3.0.5
