### ISSUE TITLE
Server Name Idication (SNI)

### ISSUE THREAD

**Issue by vchrisb** [EMCECS/ecs-object-client-java#2]
The ecs-object-client-java has as a dependency the [smart-client-java](https://github.com/EMCECS/smart-client-java) which is using [apache httpclient version 4.2.6](https://github.com/EMCECS/smart-client-java/blob/master/build.gradle#L42). See [issue 2](https://github.com/EMCECS/smart-client-java/issues/2)

Therefore does the ecs-object-client-java not support SNI with the default client.

Configuring the S3JerseyClient  to use HttpURLConnection does allow the usage of SNI for TLS.
The usage is described in the [wiki](https://github.com/EMCECS/ecs-object-client-java/wiki#a-note-on-performance)

**Comment by twincitiesguy** [comment]
Closing.  Please reference smart-client-java [issue 2](https://github.com/EMCECS/smart-client-java/issues/2).
