### ISSUE TITLE
QueryObjectsRequest class does not currently support using a filtering prefix 

### ISSUE THREAD

**Issue by OohDark30** [EMCECS/ecs-object-client-java#33]
The current implementation of the **QueryObjectsRequest** class does not currently support using a filtering prefix.  Can we add attributes for prefix and delimiter to this class to support clients wanting to utilize this standard S3 feature?

**Comment by dunedodo** [comment]
> The current implementation of the **QueryObjectsRequest** class does not currently support using a filtering prefix. Can we add attributes for prefix and delimiter to this class to support clients wanting to utilize this standard S3 feature?

Greetings! I just checked the latest release, and the request has been fulfilled. And if you find that this is still a problem, please feel free to open a new one.
